name: Executar Radar D1 US PDV

on:
  schedule:
    # roda às 18:45 (UTC‑3 Brasília) de segunda a sexta
    - cron: '45 21 * * 1-5'
  workflow_dispatch:

jobs:
  run-radar:
    runs-on: ubuntu-latest

    steps:
      # 1) Puxa o código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Prepara o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Instala bibliotecas
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas yfinance

      # 4) Executa o script, usando os secrets para Telegram
      - name: Run radar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python radar.py
