name: 🚀 Executar Radar H1 US PDV

on:
  schedule:
    # dispara todo hora entre os minutos :27 e :35 (UTC)
    # a guarda abaixo espera até :31 NY e só roda se for 10–16 NY
    - cron: "27-35 * * * 1-5"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    concurrency:
      group: radar-h1
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Mira 10:31–16:31 de Nova York
      # :27–:31 -> espera até :31 (+GRACE_SEC); :32–:35 -> roda; fora disso -> não roda
      - name: Check New York window (target :31 NY)
        id: window
        shell: bash
        env:
          GRACE_SEC: "10"   # folga após :31 (ajuste para 15–20 se precisar)
        run: |
          NY_HOUR=$(TZ=America/New_York date +%H)
          NY_MIN=$(TZ=America/New_York date +%M)
          NY_SEC=$(TZ=America/New_York date +%S)
          echo "NY now: ${NY_HOUR}:${NY_MIN}:${NY_SEC}"

          if [ "$NY_HOUR" -lt 10 ] || [ "$NY_HOUR" -gt 16 ]; then
            echo "run=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [ "$NY_MIN" -ge 27 ] && [ "$NY_MIN" -le 31 ]; then
            WAIT=$(( (31 - NY_MIN)*60 - NY_SEC + ${GRACE_SEC} ))
            if [ $WAIT -gt 0 ]; then
              echo "Aguardando ${WAIT}s para executar no :31 NY (+${GRACE_SEC}s)."
              sleep $WAIT
            fi
            echo "run=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [ "$NY_MIN" -ge 32 ] && [ "$NY_MIN" -le 35 ]; then
            echo "run=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "run=false" >> $GITHUB_OUTPUT

      - name: Install deps
        if: steps.window.outputs.run == 'true'
        run: pip install --no-cache-dir yfinance pandas requests

      - name: Run radar H1 script
        if: steps.window.outputs.run == 'true'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID_H1: ${{ secrets.TELEGRAM_CHAT_ID_H1 }}
          TELEGRAM_THREAD_ID_H1: ${{ secrets.TELEGRAM_THREAD_ID_H1 }}
        run: python radar_h1.py
