name: 🚀 Executar Radar H1 US PDV

on:
  schedule:
    - cron: "31 * * * 1-5"   # dispara todo hora às :31 UTC (a guarda abaixo garante 10:31–16:31 NY)
  workflow_dispatch: {}      # permite rodar manualmente

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    concurrency:
      group: radar-h1
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"    # <- sem cache (resolve o erro que você viu)

      # Guarda de janela: só executa às 10:31–16:31 no fuso de Nova York
      - name: Check New York window (10:31–16:31 NY)
        id: window
        shell: bash
        run: |
          NY_HOUR=$(TZ=America/New_York date +%H)
          NY_MIN=$(TZ=America/New_York date +%M)
          echo "ny_hour=$NY_HOUR" >> $GITHUB_OUTPUT
          echo "ny_min=$NY_MIN"   >> $GITHUB_OUTPUT
          if [ "$NY_MIN" = "31" ] && [ "$NY_HOUR" -ge 10 ] && [ "$NY_HOUR" -le 16 ]; then
            echo "run=true"  >> $GITHUB_OUTPUT
          else
            echo "run=false" >> $GITHUB_OUTPUT
          fi
          echo "NY time: ${NY_HOUR}:${NY_MIN}"

      - name: Install deps
        if: steps.window.outputs.run == 'true'
        run: pip install --no-cache-dir yfinance pandas requests

      - name: Run radar H1 script
        if: steps.window.outputs.run == 'true'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID_H1: ${{ secrets.TELEGRAM_CHAT_ID_H1 }}
          TELEGRAM_THREAD_ID_H1: ${{ secrets.TELEGRAM_THREAD_ID_H1 }}
        run: python radar_h1.py
