name: 🚀 Executar Radar H1 US PDV

on:
  schedule:
    # Mar–Out (EDT = UTC-4) → 10–16 NY = 14–20 UTC
    - cron: "27-40 14-20 * 3-10 1-5"
    # Jan–Fev e Nov–Dez (EST = UTC-5) → 10–16 NY = 15–21 UTC
    - cron: "27-40 15-21 * 1,2,11,12 1-5"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    concurrency:
      group: radar-h1
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # :27–:31 → espera até :31 NY (+GRACE); :32–:40 → roda; fora disso → não roda
      - name: Check New York window (target :31 NY)
        id: window
        shell: bash
        env:
          GRACE_SEC: "15"
        run: |
          NY_HOUR=$(TZ=America/New_York date +%H)
          NY_MIN=$(TZ=America/New_York date +%M)
          NY_SEC=$(TZ=America/New_York date +%S)
          echo "NY now: ${NY_HOUR}:${NY_MIN}:${NY_SEC}"

          if [ "$NY_HOUR" -lt 10 ] || [ "$NY_HOUR" -gt 16 ]; then
            echo "run=false" >> $GITHUB_OUTPUT; exit 0
          fi

          if [ "$NY_MIN" -ge 27 ] && [ "$NY_MIN" -le 31 ]; then
            WAIT=$(( (31 - NY_MIN)*60 - NY_SEC + ${GRACE_SEC} ))
            [ $WAIT -gt 0 ] && echo "Aguardando ${WAIT}s para :31 NY..." && sleep $WAIT
            echo "run=true" >> $GITHUB_OUTPUT; exit 0
          fi

          if [ "$NY_MIN" -ge 32 ] && [ "$NY_MIN" -le 40 ]; then
            echo "run=true" >> $GITHUB_OUTPUT; exit 0
          fi

          echo "run=false" >> $GITHUB_OUTPUT

      - name: Install deps
        if: steps.window.outputs.run == 'true' || github.event_name == 'workflow_dispatch'
        run: pip install --no-cache-dir yfinance pandas requests

      - name: Run radar H1 script
        if: steps.window.outputs.run == 'true' || github.event_name == 'workflow_dispatch'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID_H1: ${{ secrets.TELEGRAM_CHAT_ID_H1 }}
          TELEGRAM_THREAD_ID_H1: ${{ secrets.TELEGRAM_THREAD_ID_H1 }}
        run: python radar_h1.py
