name: 🚀 Executar Radar D1 US PDV

on:
  schedule:
    # 45 21 UTC → 18:45 BRT, segunda a sexta
    - cron: '45 21 * * 1-5'
  workflow_dispatch:

jobs:
  run-radar:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # <-- adicionamos o pandas_market_calendars aqui
          pip install requests pandas yfinance pandas_market_calendars

      - name: Run radar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python radar.py
