name: 🚀 Executar Radar D1 US PDV

on:
  schedule:
    # Seg–Sex às 21:45 UTC = 18:45 BRT
    - cron: '45 21 * * 1-5'
  workflow_dispatch:

jobs:
  run-radar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests pandas_market_calendars pytz

      - name: Run Radar Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python radar.py
